services:
  postgres:
    image: postgres:latest
    env_file:
      - ecommers/.env
    ports:
      - "5434:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ecommers/.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgresql-data:
  static-data:


